title: Melissa Voda # your name here
logo: "/images/mel.jpg" # your photo here
description:  # your text below
  Data Analyst who loves Data Visualization | Excel | Tableau | SQL
  <br><br>
  Who also loves gaming, reading and bacon cheeseburgers!
  <br><br>
 <p align="center">
 <a href="https://www.linkedin.com/in/melvoda/"><img src="images/linkedin_icon.png?raw=true"/> |
 <a href="https://public.tableau.com/app/profile/melissa.voda"><img src="images/tableau_icon.png?raw=true"/> | 
 <a href="https://melissavoda.carrd.co/"><img src="images/github_icon.png?raw=true"/> |
 <a href="https://github.com/melissavoda/"><img src="images/github_icon.png?raw=true"/></p>
  

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
