title: Melissa Voda 
logo: "/images/mel.jpg" 
description:

  <br>
  Data Analyst who loves Data Visualization | Excel | Tableau | SQL
  <br><br>
  Who also loves gaming, reading and bacon cheeseburgers!
  <br><br>
  

 <a href="https://github.com/melissavoda/"><img src="images/github_icon.png"/> &emsp;
 <a href="https://www.linkedin.com/in/melvoda/"><img src="images/linkedin_icon.png"/> &emsp;
 <a href="https://public.tableau.com/app/profile/melissa.voda"><img src="images/tableau_icon.png"/> &emsp;
 <a href="https://melissavoda.carrd.co/"><img src="images/web_icon.png"/>
 

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
