title: Melissa Voda # your name (or website title) here
logo: "" # your photo (or logo) here
description:  # your text below (remove <br> elements if you don't need line breaks)
<br>
  Data Analyst || More About Me Goes Here 
<br>
<a href="https://www.linkedin.com/in/melvoda/">LinkedIn Profile</a> | <a href="https://public.tableau.com/">Tableau Profile</a> 


  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
