title: Melissa Voda # your name (or website title) here
logo: "/images/cat.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  1st Photo
  <br><br>
  <img src = "/images/cat.jpg" alt ="photo1">
  <br>
  2nd Photo
  <br>
  <img src = "/images/cat2.png" alt ="photo2">

  
  <a href="https://www.linkedin.com/in/melvoda/">My LinkedIn Profile</a>  | <a href="https://public.tableau.com/">Tableau Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
