title: Melissa Voda # your name here
logo: "/images/mel.jpg" # your photo here
description:  # your text below
  Data Analyst who loves Data Visualization | Excel | Tableau | SQL
  <br><br>
  Who also loves gaming, reading and bacon cheeseburgers!
  <br><br>

  
 <a href="https://www.linkedin.com/in/melvoda/">LinkedIn</a>  | <a href="https://public.tableau.com/app/profile/melissa.voda">Tableau</a> | 
 <a href="https://melissavoda.carrd.co/">Portfolio</a>
  

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
