title: Melissa Voda # your name here
logo: "/images/cat2.png" # your photo here
description:  # your text below
  Data Analyst | SQL | Tableau | Excel | Data Visualization
  <br>
  Who also loves gaming, reading and bacon Cheeseburgers!
  <br>

  
 <a href="https://www.linkedin.com/in/melvoda/">LinkedIn Profile</a>  | <a href="https://public.tableau.com/app/profile/melissa.voda">Tableau Profile</a> | 
 <a href="https://melissavoda.carrd.co/">Personal Portfolio</a>
  

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
