title: Melissa Voda # your name (or website title) here
logo: "" # your photo (or logo) here
<img src = "/images/logo.png">
description:  # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst || Data Visualization || SQL || Tableau || Excel 
  <br><br>
  <a href="https://www.linkedin.com/in/melvoda/">View My LinkedIn Profile</a> 
  <img src = "/images/logo.png">

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
